name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - feature*
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy_resources:
    runs-on: ubuntu-latest
    container:
      image: azotamiota/terraform-tools:latest
      options: --user root
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Code quality tests
        run: pwd;ls -lart;pre-commit -V;sudo pre-commit install
        # continue-on-error: true
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "GPG key imported successfully"
      - name: Decrypt Secrets
        run: ./secrets/decrypt_secrets.sh
      - name: Initialise Terraform
        run: cd terraform && terraform init
      - name: Terraform plan
        run: cd terraform && terraform plan -out tfplan.output
