name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - private*
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute first command
        run: |
          pwd
          echo "Hello World from GitHub Actions"
  deploy_resources:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Terraform
        run: ./scripts/install_tfenv.sh
      - name: Code quality tests
        run: ./scripts/pre-commit.sh
        continue-on-error: true
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "GPG key imported successfully"
      - name: Decrypt Secrets
        run: ./secrets/decrypt_secrets.sh
      - name: Initialise Terraform
        run: cd terraform && terraform init
      - name: Terraform plan
        run: cd terraform && terraform plan -var-file=../secrets/decrypted_secrets/terraform.tfvars
