name: Terraform Deployment Pipeline

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Execute first command
        run: echo "Hello World from GitHub Actions"

      # - name: Execute decrypt.sh
      #   run: bash decrypt.sh

  # plan:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v2

  #     - name: Terraform Init
  #       run: terraform init

  #     - name: Terraform Plan
  #       run: terraform plan -out=tfplan

  #     - name: Upload Terraform Plan Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: tfplan
  #         path: tfplan

  # apply:
  #   runs-on: ubuntu-latest
  #   needs: plan
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v2

  #     - name: Download Terraform Plan Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: tfplan
  #         path: .

  #     - name: Terraform Apply
  #       run: terraform apply tfplan